security:
  oauth2:
    client:
      access-token-uri: https://api.fitbit.com/oauth2/token
      user-authorization-uri: https://www.fitbit.com/oauth2/authorize
      token-name: access_token
      authentication-scheme: header
      client-authentication-scheme: header
      scope: profile
    resource:
      token-type: Bearer
      user-info-uri: https://api.fitbit.com/1/user/-/profile.json
spring.resources.chain.enabled: true
