-- MySQL Script generated by MySQL Workbench
-- 03/31/16 10:52:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema food
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food` DEFAULT CHARACTER SET latin1 ;
USE `food` ;

-- -----------------------------------------------------
-- Table `food`.`fc_celiac_members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_celiac_members` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_celiac_members` (
  `CODE` VARCHAR(255) NOT NULL DEFAULT '',
  `FIRST_NAME` VARCHAR(255) NOT NULL DEFAULT '',
  `LAST_NAME` VARCHAR(255) NOT NULL DEFAULT '',
  `CREATED` DATETIME NULL DEFAULT NULL,
  `MODIFIED` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_diet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_diet` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_diet` (
  `DIETID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `DIETNM` VARCHAR(255) NOT NULL,
  `DENGNM` VARCHAR(255) NOT NULL,
  `DIETDESC` TEXT NOT NULL,
  `DENGDESC` TEXT NOT NULL,
  `AUTHORID` INT(11) NOT NULL,
  PRIMARY KEY (`DIETID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_ematerials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_ematerials` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_ematerials` (
  `EMID` INT(11) NOT NULL,
  `EDUMAT` BLOB NOT NULL,
  `EMENG` BLOB NOT NULL,
  `DATEGEN` DATE NOT NULL,
  `DATEREV` DATE NOT NULL,
  `TRID` INT(11) NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`EMID`),
  INDEX `TRID` (`TRID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_exchangesystem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_exchangesystem` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_exchangesystem` (
  `FGID` INT(11) NOT NULL,
  `COMPID` VARCHAR(25) NOT NULL,
  `MIN` INT(11) NOT NULL,
  `MAXL` INT(11) NOT NULL,
  `MAXU` INT(11) NOT NULL,
  `UNIT` VARCHAR(25) NOT NULL,
  `SOURCEID` INT(11) NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  INDEX `FGID` (`FGID` ASC),
  INDEX `COMPID` (`COMPID` ASC),
  INDEX `SOURCEID` (`SOURCEID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_ffq_pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_ffq_pictures` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_ffq_pictures` (
  `StepId` INT(10) NOT NULL DEFAULT '0',
  `FoodName` VARCHAR(255) NOT NULL DEFAULT '',
  `Size` VARCHAR(32) CHARACTER SET 'latin1' NOT NULL DEFAULT '',
  `FFQ_ID` INT(11) NULL DEFAULT NULL,
  `Picture` LONGBLOB NULL DEFAULT NULL,
  `Weight` DECIMAL(10,5) NULL DEFAULT NULL,
  `WeightDesc` VARCHAR(255) NULL DEFAULT NULL,
  `Ts` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`StepId`, `FoodName`, `Size`),
  INDEX `ByFFQ` (`FFQ_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_ffq_steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_ffq_steps` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_ffq_steps` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `FFQ_ID` INT(10) NOT NULL DEFAULT '0',
  `Question` VARCHAR(255) NULL DEFAULT NULL,
  `StepNumber` INT(11) NOT NULL DEFAULT '1',
  `Type` VARCHAR(50) NULL DEFAULT NULL,
  `Instructions` TEXT NULL DEFAULT NULL,
  `AllowSkipTo` INT(11) NULL DEFAULT NULL,
  `FoodCodes` TEXT NULL DEFAULT NULL,
  `WeightS` DECIMAL(10,5) NULL DEFAULT NULL,
  `WeightTextS` VARCHAR(255) NULL DEFAULT NULL,
  `WeightM` DECIMAL(10,5) NULL DEFAULT NULL,
  `WeightTextM` VARCHAR(255) NULL DEFAULT NULL,
  `WeightL` DECIMAL(10,5) NULL DEFAULT NULL,
  `WeightTextL` VARCHAR(255) NULL DEFAULT NULL,
  `WeightXL` DECIMAL(10,5) NULL DEFAULT NULL,
  `WeightTextXL` VARCHAR(255) NULL DEFAULT NULL,
  `WeightXXL` DECIMAL(10,5) NULL DEFAULT NULL,
  `WeightTextXXL` VARCHAR(255) NULL DEFAULT NULL,
  `WeightXXXL` DECIMAL(10,5) NULL DEFAULT NULL,
  `WeightTextXXXL` VARCHAR(255) NULL DEFAULT NULL,
  `Frequency1` VARCHAR(25) NULL DEFAULT NULL,
  `Frequency2` VARCHAR(25) NULL DEFAULT NULL,
  `Frequency3` VARCHAR(25) NULL DEFAULT NULL,
  `Frequency4` VARCHAR(25) NULL DEFAULT NULL,
  `Frequency5` VARCHAR(25) NULL DEFAULT NULL,
  `Frequency6` VARCHAR(25) NULL DEFAULT NULL,
  `Frequency7` VARCHAR(25) NULL DEFAULT NULL,
  `Frequency8` VARCHAR(25) NULL DEFAULT NULL,
  `Frequency9` VARCHAR(25) NULL DEFAULT NULL,
  `Frequency10` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ByFFQ` (`FFQ_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_ffq_warnings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_ffq_warnings` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_ffq_warnings` (
  `ID` INT(10) NOT NULL DEFAULT '0',
  `Result` VARCHAR(255) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_ffqs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_ffqs` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_ffqs` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `ContentId` INT(11) NULL DEFAULT NULL,
  `Recurrence` VARCHAR(50) NULL DEFAULT NULL,
  `OnlyMediumSize` TINYINT(4) NOT NULL DEFAULT '0',
  `AllSizes` TINYINT(4) NOT NULL DEFAULT '0',
  `RemarksLabel` VARCHAR(255) NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT NULL,
  `Modified` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_foodalternatives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_foodalternatives` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_foodalternatives` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DIETID` INT(11) NOT NULL,
  `ORIGFDCD` VARCHAR(25) NOT NULL,
  `ALTFDCD` VARCHAR(25) NOT NULL,
  `AFAMFAC` DECIMAL(10,5) NOT NULL,
  `AUTHORID` INT(11) NOT NULL,
  `DATEGEN` DATETIME NOT NULL,
  `DATEREV` DATETIME NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Index 2` (`ORIGFDCD` ASC, `DIETID` ASC, `ALTFDCD` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_foodgroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_foodgroup` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_foodgroup` (
  `FGNM` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `FGCD` INT(11) NOT NULL,
  `FGENGNM` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `FGDESC` TEXT CHARACTER SET 'utf8' NOT NULL,
  `FGENGDESC` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`FGCD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `food`.`fc_foodprices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_foodprices` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_foodprices` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `FOODID` VARCHAR(25) NULL DEFAULT NULL,
  `PRICE` DECIMAL(15,2) NULL DEFAULT NULL,
  `CURRENCY` VARCHAR(10) NULL DEFAULT NULL,
  `STOREID` INT(11) NULL DEFAULT NULL,
  `WEIGHT` DECIMAL(15,2) NULL DEFAULT NULL,
  `UNIT` VARCHAR(50) NULL DEFAULT NULL,
  `USERID` INT(11) NULL DEFAULT NULL,
  `DATEGEN` DATETIME NULL DEFAULT NULL,
  `DATEREV` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ByFood` (`FOODID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_foodquestionnaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_foodquestionnaire` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_foodquestionnaire` (
  `FQCD` INT(11) NOT NULL,
  `GSAMIN` DECIMAL(10,5) NOT NULL,
  `GSAMAX` DECIMAL(10,5) NOT NULL,
  `GRADEA` VARCHAR(255) NOT NULL,
  `GSBMIN` DECIMAL(10,5) NOT NULL,
  `GSBMAX` DECIMAL(10,5) NOT NULL,
  `GRADEB` VARCHAR(255) NOT NULL,
  `GSCMIN` DECIMAL(10,5) NOT NULL,
  `GSCMAX` DECIMAL(10,5) NOT NULL,
  `GRADEC` VARCHAR(255) NOT NULL,
  `AUTHID` INT(11) NOT NULL,
  `DATEGEN` DATETIME NOT NULL,
  `DATEREV` DATETIME NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`FQCD`),
  INDEX `AUTHID` (`AUTHID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_foodstores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_foodstores` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_foodstores` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NULL DEFAULT NULL,
  `ACTIVE` TINYINT(4) NOT NULL DEFAULT '0',
  `USERID` INT(11) NULL DEFAULT NULL,
  `DATEGEN` DATETIME NULL DEFAULT NULL,
  `DATEREV` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_foodsubgroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_foodsubgroup` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_foodsubgroup` (
  `FSGCD` INT(11) NOT NULL,
  `FSGNM` VARCHAR(255) NOT NULL,
  `FSGENGNM` VARCHAR(255) NOT NULL,
  `FGCD` INT(11) NOT NULL,
  `FDBFID` VARCHAR(25) NOT NULL,
  `FDSFKID` VARCHAR(25) NOT NULL,
  `FDUSDAID` VARCHAR(25) NOT NULL,
  `FDINDID` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`FSGCD`),
  INDEX `fk_fc_foodsubgroup_fc_foodgroup1_idx` (`FGCD` ASC),
  CONSTRAINT `fk_fc_foodsubgroup_fc_foodgroup1`
    FOREIGN KEY (`FGCD`)
    REFERENCES `food`.`fc_foodgroup` (`FGCD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_fqquestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_fqquestions` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_fqquestions` (
  `FQCD` INT(11) NOT NULL,
  `QCD` INT(11) NOT NULL,
  `QUES` TEXT NOT NULL,
  `INSTR` VARCHAR(255) NOT NULL,
  `COMMENT` VARCHAR(255) NOT NULL,
  `ANS1` VARCHAR(255) NOT NULL,
  `POINTS1` INT(11) NOT NULL,
  `ANS2` VARCHAR(255) NOT NULL,
  `POINTS2` INT(11) NOT NULL,
  `ANS3` VARCHAR(255) NOT NULL,
  `POINTS3` INT(11) NOT NULL,
  `ANS4` VARCHAR(255) NOT NULL,
  `POINTS4` INT(11) NOT NULL,
  `ANS5` VARCHAR(255) NOT NULL,
  `POINTS5` INT(11) NOT NULL,
  `ANS6` VARCHAR(255) NOT NULL,
  `POINTS6` INT(11) NOT NULL,
  `ANS7` VARCHAR(255) NOT NULL,
  `POINTS7` INT(11) NOT NULL,
  `ANS8` VARCHAR(255) NOT NULL,
  `POINTS8` INT(11) NOT NULL,
  `ANS9` VARCHAR(255) NOT NULL,
  `POINTS9` INT(11) NOT NULL,
  `ANS10` VARCHAR(255) NOT NULL,
  `POINTS10` INT(11) NOT NULL,
  `PMAX` INT(11) NOT NULL,
  `ORDER` INT(11) NOT NULL,
  PRIMARY KEY (`QCD`),
  INDEX `FQCD` (`FQCD` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_gastro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_gastro` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_gastro` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ENGNAME` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `CREATED` DATETIME NULL DEFAULT NULL,
  `MODIFIED` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `food`.`fc_groupofpeople`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_groupofpeople` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_groupofpeople` (
  `GPID` INT(11) NOT NULL,
  `GPNM` VARCHAR(255) NOT NULL DEFAULT '',
  `GPENGNM` VARCHAR(255) NOT NULL DEFAULT '',
  `GPDESC` TEXT NOT NULL,
  `GPENGDESC` TEXT NOT NULL,
  `SEX` VARCHAR(255) NOT NULL DEFAULT '',
  `MIN` INT(11) NOT NULL,
  `MAX` INT(11) NOT NULL,
  `UNIT` VARCHAR(255) NOT NULL DEFAULT '',
  `WEIGHT` DECIMAL(10,5) NULL DEFAULT NULL,
  `HEIGHT` DECIMAL(10,5) NULL DEFAULT NULL,
  `SOURCEID` INT(11) NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`GPID`),
  INDEX `SOURCEID` (`SOURCEID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_gs1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_gs1` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_gs1` (
  `FOODID` VARCHAR(25) NOT NULL,
  `GS1` VARCHAR(255) NOT NULL,
  `DISTRIB` VARCHAR(255) NULL DEFAULT NULL,
  `COUNTRY` VARCHAR(255) NULL DEFAULT NULL,
  `PRODUCER` VARCHAR(255) NULL DEFAULT NULL,
  `REMARKS` VARCHAR(255) NULL DEFAULT NULL,
  `DATEGEN` DATETIME NULL DEFAULT NULL,
  `DATEREV` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`FOODID`, `GS1`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_guidelines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_guidelines` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_guidelines` (
  `GPID` INT(11) NOT NULL,
  `COMPID` VARCHAR(25) NOT NULL,
  `FGID` VARCHAR(25) NOT NULL,
  `MEALCD` VARCHAR(25) NOT NULL,
  `VALUE` DECIMAL(10,5) NOT NULL,
  `MIN` DECIMAL(10,5) NOT NULL,
  `MAX` DECIMAL(10,5) NOT NULL,
  `UNIT` VARCHAR(255) NOT NULL,
  `VALTYPE` VARCHAR(255) NOT NULL,
  `SOURCEID` INT(11) NOT NULL,
  `DATEGEN` DATETIME NOT NULL,
  `DATEREV` DATETIME NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`GPID`, `COMPID`, `FGID`, `MEALCD`),
  INDEX `GPID` (`GPID` ASC),
  INDEX `COMPID` (`COMPID` ASC),
  INDEX `FGID` (`FGID` ASC),
  INDEX `SOURCEID` (`SOURCEID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `food`.`fc_householdmeasure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_householdmeasure` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_householdmeasure` (
  `HMCD` INT(11) NOT NULL AUTO_INCREMENT,
  `HMNM` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `HMENGNM` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  PRIMARY KEY (`HMCD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `food`.`fc_kulinarika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_kulinarika` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_kulinarika` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) NOT NULL,
  `DATEGEN` DATETIME NULL DEFAULT NULL,
  `DATEREV` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_lllclassroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_lllclassroom` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_lllclassroom` (
  `USERID` INT(11) NOT NULL,
  `LLLMID` INT(11) NOT NULL,
  `DATE` DATETIME NOT NULL,
  `GRADE` DECIMAL(10,5) NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  INDEX `USERID` (`USERID` ASC),
  INDEX `LLLMID` (`LLLMID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_lllmodul`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_lllmodul` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_lllmodul` (
  `LLLMID` INT(11) NOT NULL,
  `LLLMNM` VARCHAR(255) NOT NULL DEFAULT '',
  `LLLMC` TEXT NOT NULL,
  `TRID` INT(11) NOT NULL,
  `DATEGEN` DATE NOT NULL,
  `DATEREV` DATE NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`LLLMID`),
  INDEX `TRID` (`TRID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_llltest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_llltest` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_llltest` (
  `LLLMID` INT(11) NOT NULL,
  `LLLMQ` VARCHAR(255) NOT NULL,
  `LLLMAA` VARCHAR(255) NOT NULL DEFAULT '',
  `LLLMAB` VARCHAR(255) NOT NULL DEFAULT '',
  `LLLMAC` VARCHAR(255) NOT NULL DEFAULT '',
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`LLLMQ`),
  INDEX `LLLMID` (`LLLMID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_food` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_food` (
  `ORIGFDCD` VARCHAR(25) NOT NULL,
  `ORIGFDNM` VARCHAR(255) NOT NULL DEFAULT '',
  `ENGFDNAM` VARCHAR(255) NOT NULL DEFAULT '',
  `SCINAM` VARCHAR(255) NOT NULL DEFAULT '',
  `CDXFDSTD` VARCHAR(255) NOT NULL DEFAULT '',
  `GS1` VARCHAR(255) NOT NULL DEFAULT '',
  `ENR` VARCHAR(255) NOT NULL DEFAULT '',
  `INS` VARCHAR(255) NOT NULL DEFAULT '',
  `ORIGGPCD` VARCHAR(25) NOT NULL DEFAULT '',
  `FSGCD` INT(11) NULL DEFAULT NULL,
  `PRODTYPE` VARCHAR(255) NOT NULL,
  `CDXFDADD` VARCHAR(255) NOT NULL DEFAULT '',
  `CDXFDFD` VARCHAR(255) NOT NULL DEFAULT '',
  `CDXCONT` VARCHAR(255) NOT NULL DEFAULT '',
  `FAOFBS` VARCHAR(255) NOT NULL DEFAULT '',
  `CIAA` VARCHAR(255) NOT NULL DEFAULT '',
  `EC2` VARCHAR(255) NOT NULL DEFAULT '',
  `FOODSRCE` VARCHAR(255) NOT NULL,
  `PARTPLAN` VARCHAR(255) NOT NULL,
  `PHYSTATE` VARCHAR(255) NOT NULL,
  `HEATREAT` VARCHAR(255) NOT NULL,
  `COOKMETH` VARCHAR(255) NOT NULL,
  `TREATAPP` VARCHAR(255) NOT NULL,
  `PRESMETH` VARCHAR(255) NOT NULL,
  `PACKMED` VARCHAR(255) NOT NULL,
  `CONTWRPG` VARCHAR(255) NOT NULL,
  `FDCTSRFC` VARCHAR(255) NOT NULL,
  `LBLCLAIM` VARCHAR(255) NOT NULL,
  `AREAORIG` VARCHAR(255) NOT NULL,
  `AREAPROC` VARCHAR(255) NOT NULL DEFAULT '',
  `AREACONS` VARCHAR(255) NOT NULL DEFAULT '',
  `PRODENVIR` VARCHAR(255) NOT NULL,
  `AGRICOND` VARCHAR(255) NOT NULL DEFAULT '',
  `GROWCOND` VARCHAR(255) NOT NULL DEFAULT '',
  `MATURITY` VARCHAR(255) NOT NULL DEFAULT '',
  `GENMOD` VARCHAR(255) NOT NULL DEFAULT '',
  `CUISINE` VARCHAR(255) NOT NULL DEFAULT '',
  `ADJUNCT` VARCHAR(255) NOT NULL DEFAULT '',
  `INGLIST` VARCHAR(255) NOT NULL DEFAULT '',
  `FINLPREP` VARCHAR(255) NOT NULL DEFAULT '',
  `SERVSIZE` VARCHAR(255) NOT NULL DEFAULT '',
  `SERVPACK` DECIMAL(10,5) NOT NULL,
  `SERVSUGG` VARCHAR(255) NOT NULL DEFAULT '',
  `PREPSTATE` TINYINT(1) NOT NULL,
  `YIELD` VARCHAR(25) NOT NULL,
  `ALLERGEN` VARCHAR(255) NOT NULL DEFAULT '',
  `DIETCLAIM` VARCHAR(255) NOT NULL DEFAULT '',
  `EDPORTNAT` VARCHAR(255) NOT NULL DEFAULT '',
  `WASTENAT` VARCHAR(255) NOT NULL DEFAULT '',
  `COLOR` VARCHAR(255) NOT NULL DEFAULT '',
  `GENIMAGE` VARCHAR(255) NOT NULL DEFAULT '',
  `SPCIMAGE` VARCHAR(255) NOT NULL DEFAULT '',
  `PRODUCER` VARCHAR(255) NOT NULL DEFAULT '',
  `DISTRIB` VARCHAR(255) NOT NULL DEFAULT '',
  `SOURCEID` VARCHAR(25) NULL DEFAULT NULL,
  `COUNTRY` VARCHAR(255) NULL DEFAULT NULL,
  `DIETID` VARCHAR(255) NULL DEFAULT NULL,
  `GASTROID` VARCHAR(255) NULL DEFAULT NULL,
  `FOODEX2` VARCHAR(255) NULL DEFAULT NULL,
  `KULINARIKA_CAT` INT(11) NULL DEFAULT NULL,
  `KULINARIKA_SUBCAT` INT(11) NULL DEFAULT NULL,
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  `ACTIVE` CHAR(1) NOT NULL DEFAULT '',
  `DATEGEN` DATETIME NULL DEFAULT NULL,
  `DATEREV` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ORIGFDCD`),
  INDEX `fk_fir_food_fc_foodsubgroup1_idx` (`FSGCD` ASC),
  CONSTRAINT `fk_fir_food_fc_foodsubgroup1`
    FOREIGN KEY (`FSGCD`)
    REFERENCES `food`.`fc_foodsubgroup` (`FSGCD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_mapping` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_mapping` (
  `FDNM` VARCHAR(255) NOT NULL,
  `FDENGNM` VARCHAR(255) NOT NULL,
  `FDBFID` VARCHAR(25) NOT NULL,
  `FDSFKID` VARCHAR(25) NOT NULL,
  `FDUSDAID` VARCHAR(25) NOT NULL,
  `FDINDID` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`FDBFID`, `FDSFKID`, `FDUSDAID`, `FDINDID`),
  INDEX `fk_fc_mapping_fir_food2_idx` (`FDSFKID` ASC),
  INDEX `fk_fc_mapping_fir_food3_idx` (`FDUSDAID` ASC),
  INDEX `fk_fc_mapping_fir_food4_idx` (`FDINDID` ASC),
  CONSTRAINT `fk_fc_mapping_fir_food1`
    FOREIGN KEY (`FDBFID`)
    REFERENCES `food`.`fir_food` (`ORIGFDCD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fc_mapping_fir_food2`
    FOREIGN KEY (`FDSFKID`)
    REFERENCES `food`.`fir_food` (`ORIGFDCD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fc_mapping_fir_food3`
    FOREIGN KEY (`FDUSDAID`)
    REFERENCES `food`.`fir_food` (`ORIGFDCD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fc_mapping_fir_food4`
    FOREIGN KEY (`FDINDID`)
    REFERENCES `food`.`fir_food` (`ORIGFDCD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_mappingind`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_mappingind` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_mappingind` (
  `FDNM` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `FDENGNM` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `FDBFID` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `FDSFKID` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `FDUSDAID` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `FDINDID` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `food`.`fc_meal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_meal` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_meal` (
  `MEALCD` VARCHAR(25) NOT NULL,
  `MEALNM` VARCHAR(255) NOT NULL,
  `MENGNM` VARCHAR(255) NOT NULL,
  `FROM` TIME NULL DEFAULT NULL,
  `TO` TIME NULL DEFAULT NULL,
  `GROUP` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`MEALCD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_menucls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_menucls` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_menucls` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_menutags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_menutags` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_menutags` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `CLSID` INT(10) NULL DEFAULT '0',
  `NAME` VARCHAR(255) NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  INDEX `CLS` (`CLSID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_municipality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_municipality` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_municipality` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) NULL DEFAULT '0',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_pal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_pal` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_pal` (
  `PAID` INT(11) NOT NULL AUTO_INCREMENT,
  `PAG` VARCHAR(255) NOT NULL,
  `PADESC` VARCHAR(255) NOT NULL DEFAULT '',
  `PAENGDESC` VARCHAR(255) NOT NULL DEFAULT '',
  `SEX` VARCHAR(1) NOT NULL,
  `PAL` DECIMAL(10,5) NOT NULL,
  `METS` DECIMAL(10,5) NOT NULL,
  `UNIT` VARCHAR(25) NOT NULL,
  `SOURCEID` VARCHAR(25) NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL,
  `TYPE` CHAR(10) NULL DEFAULT 'A',
  PRIMARY KEY (`PAID`),
  INDEX `SOURCEID` (`SOURCEID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_percentile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_percentile` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_percentile` (
  `SEX` VARCHAR(1) NOT NULL,
  `MONTH` INT(11) NOT NULL,
  `TYPE` VARCHAR(50) NULL DEFAULT NULL,
  `L` DOUBLE NULL DEFAULT NULL,
  `M` DOUBLE NULL DEFAULT NULL,
  `S` DOUBLE NULL DEFAULT NULL,
  `P1` DOUBLE NULL DEFAULT NULL,
  `P3` DOUBLE NULL DEFAULT NULL,
  `P5` DOUBLE NULL DEFAULT NULL,
  `P10` DOUBLE NULL DEFAULT NULL,
  `P15` DOUBLE NULL DEFAULT NULL,
  `P25` DOUBLE NULL DEFAULT NULL,
  `P50` DOUBLE NULL DEFAULT NULL,
  `P75` DOUBLE NULL DEFAULT NULL,
  `P85` DOUBLE NULL DEFAULT NULL,
  `P90` DOUBLE NULL DEFAULT NULL,
  `P95` DOUBLE NULL DEFAULT NULL,
  `P97` DOUBLE NULL DEFAULT NULL,
  `P99` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`SEX`, `MONTH`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_recall_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_recall_categories` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_recall_categories` (
  `IVZFDCD` VARCHAR(35) NOT NULL,
  `FGCD` INT(11) NOT NULL,
  `IVZFDNM` VARCHAR(255) NOT NULL,
  `ENGFDNM` VARCHAR(255) NOT NULL,
  `LEVEL` INT(11) NOT NULL,
  `FOODEX1` VARCHAR(35) NOT NULL,
  `FOODEX2` VARCHAR(35) NOT NULL,
  `ORIGFDCD` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`IVZFDCD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_recall_category_pictureweight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_recall_category_pictureweight` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_recall_category_pictureweight` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `IVZFDCD` VARCHAR(35) NULL DEFAULT NULL,
  `PICTURE` LONGBLOB NULL DEFAULT NULL,
  `WEIGHT` DECIMAL(10,5) NULL DEFAULT NULL,
  `DATEGEN` DATETIME NULL DEFAULT NULL,
  `DATEREV` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ByCode` (`IVZFDCD` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_subkulinarika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_subkulinarika` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_subkulinarika` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CATID` INT(11) NOT NULL,
  `TITLE` VARCHAR(255) NOT NULL,
  `CLASSIFIER` VARCHAR(255) NOT NULL,
  `DATEGEN` DATETIME NULL DEFAULT NULL,
  `DATEREV` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_weights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_weights` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_weights` (
  `ORIGFDCD` VARCHAR(25) NOT NULL,
  `HMCD` INT(11) UNSIGNED NOT NULL,
  `AMOUNT` DOUBLE NOT NULL,
  `IMAGE` BLOB NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fc_yieldfactors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fc_yieldfactors` ;

CREATE TABLE IF NOT EXISTS `food`.`fc_yieldfactors` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FOODID` VARCHAR(25) NULL DEFAULT NULL,
  `PREPMET` VARCHAR(255) NULL DEFAULT NULL,
  `TMIN` INT(11) NOT NULL,
  `TMAX` INT(11) NOT NULL,
  `YIELD` DECIMAL(10,5) NOT NULL,
  `YNM` VARCHAR(255) NULL DEFAULT NULL,
  `YENGNM` VARCHAR(255) NULL DEFAULT NULL,
  `RETREF` VARCHAR(25) NULL DEFAULT NULL,
  `REMARK` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_component` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_component` (
  `ECOMPID` VARCHAR(25) NOT NULL,
  `ORIGCPCD` VARCHAR(25) NOT NULL DEFAULT '',
  `ORIGCPNM` VARCHAR(255) NOT NULL DEFAULT '',
  `ENGCPNAM` VARCHAR(255) NOT NULL DEFAULT '',
  `OPTIJED` VARCHAR(25) NOT NULL,
  `IZVOR` VARCHAR(1) NOT NULL,
  `DACH` VARCHAR(25) NOT NULL,
  `DACH2` VARCHAR(25) NOT NULL,
  `CPID_USDA` VARCHAR(3) NOT NULL,
  `CPDESC` LONGTEXT NOT NULL,
  `CPMUCH` LONGTEXT NOT NULL,
  `CPLESS` LONGTEXT NOT NULL,
  `CPUNITH` VARCHAR(25) NOT NULL,
  `CPUNITP` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ECOMPID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_food_new`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_food_new` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_food_new` (
  `ORIGFDCD` VARCHAR(255) NOT NULL DEFAULT '',
  `SLO` VARCHAR(255) NULL DEFAULT NULL,
  `ENG` VARCHAR(255) NULL DEFAULT NULL,
  `SCI` VARCHAR(255) NULL DEFAULT NULL,
  `GROUP` INT(11) NULL DEFAULT NULL,
  `VIS` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ORIGFDCD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_foodnames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_foodnames` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_foodnames` (
  `ORIGFDCD` VARCHAR(25) NOT NULL,
  `FNAME` VARCHAR(255) NOT NULL DEFAULT '',
  `LANG` VARCHAR(255) NOT NULL DEFAULT '',
  `PREF` VARCHAR(255) NOT NULL DEFAULT '',
  `FNREF` VARCHAR(255) NOT NULL DEFAULT '',
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`FNAME`, `ORIGFDCD`),
  INDEX `ORIGFDCD` (`ORIGFDCD` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_recipe` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_recipe` (
  `ORIGFDCD` VARCHAR(25) NOT NULL,
  `RECID` VARCHAR(25) NOT NULL,
  `RECREF` VARCHAR(25) NOT NULL DEFAULT '',
  `RECPROC` LONGTEXT NOT NULL,
  `YIELDWAT` DECIMAL(10,5) NOT NULL,
  `AUTHOR` VARCHAR(255) NOT NULL,
  `YIELDFAT` DECIMAL(10,5) NOT NULL,
  `YIELDALC` DECIMAL(10,5) NOT NULL,
  `RETREF` VARCHAR(25) NOT NULL DEFAULT '',
  `IS_DRAINED` TINYINT(4) NOT NULL DEFAULT '0',
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`RECID`),
  INDEX `ORIGFDCD` (`ORIGFDCD` ASC),
  INDEX `RECREF` (`RECREF` ASC),
  CONSTRAINT `fk_fir_recipe_fir_food1`
    FOREIGN KEY (`ORIGFDCD`)
    REFERENCES `food`.`fir_food` (`ORIGFDCD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_ingredients` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_ingredients` (
  `RECID` VARCHAR(25) NOT NULL,
  `FOODID` VARCHAR(25) NOT NULL,
  `INGNAM` VARCHAR(255) NOT NULL DEFAULT '',
  `INGAMOUNT` DECIMAL(15,5) NOT NULL,
  `INGUNIT` VARCHAR(255) NOT NULL DEFAULT '',
  `HMID` INT(3) NOT NULL DEFAULT '0',
  `RANK` INT(11) NOT NULL,
  `EDIBLE` TINYINT(3) NOT NULL DEFAULT '0',
  `WHOLE_WHEAT` TINYINT(3) NOT NULL DEFAULT '0',
  `SOAK` TINYINT(3) NOT NULL DEFAULT '0',
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`RECID`, `FOODID`),
  INDEX `RECID` (`RECID` ASC),
  INDEX `FOODID` (`FOODID` ASC),
  CONSTRAINT `fk_fir_ingredients_fir_food1`
    FOREIGN KEY (`FOODID`)
    REFERENCES `food`.`fir_food` (`ORIGFDCD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fir_ingredients_fir_recipe1`
    FOREIGN KEY (`RECID`)
    REFERENCES `food`.`fir_recipe` (`RECID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_method` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_method` (
  `METHID` VARCHAR(25) NOT NULL DEFAULT '',
  `METHNAME` VARCHAR(255) NOT NULL DEFAULT '',
  `ORGMNAM` VARCHAR(255) NOT NULL DEFAULT '',
  `OFFICIAL` VARCHAR(255) NOT NULL DEFAULT '',
  `GENDESC` VARCHAR(255) NOT NULL DEFAULT '',
  `METHREF` VARCHAR(255) NOT NULL DEFAULT '',
  `EXTRACT` VARCHAR(255) NOT NULL DEFAULT '',
  `SEPARAT` VARCHAR(255) NOT NULL DEFAULT '',
  `IDENT` VARCHAR(255) NOT NULL DEFAULT '',
  `DETECT` VARCHAR(255) NOT NULL DEFAULT '',
  `QUANT` VARCHAR(255) NOT NULL DEFAULT '',
  `OMETHKS` VARCHAR(255) NOT NULL DEFAULT '',
  `ADDDESC` VARCHAR(255) NOT NULL DEFAULT '',
  `ANDETAIL` VARCHAR(255) NOT NULL DEFAULT '',
  `ACCURACY` VARCHAR(255) NOT NULL DEFAULT '',
  `APPLICABILITY` VARCHAR(255) NOT NULL DEFAULT '',
  `PRECISION` DECIMAL(10,5) NOT NULL,
  `REPEAT` DECIMAL(10,5) NOT NULL,
  `REPRODUC` DECIMAL(10,5) NOT NULL,
  `RECOVERY` DECIMAL(10,5) NOT NULL,
  `SELECTIV` DECIMAL(10,5) NOT NULL,
  `SENSITIV` DECIMAL(10,5) NOT NULL,
  `SPECIFIC` DECIMAL(10,5) NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`METHID`),
  INDEX `METHREF` (`METHREF` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_qualityassessment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_qualityassessment` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_qualityassessment` (
  `VALUEID` VARCHAR(25) NOT NULL,
  `QAID` VARCHAR(25) NOT NULL DEFAULT '',
  `QDESC` VARCHAR(255) NOT NULL DEFAULT '',
  `QREF` VARCHAR(25) NOT NULL DEFAULT '',
  `QFOOD` DECIMAL(10,5) NOT NULL,
  `QCOMP` DECIMAL(10,5) NOT NULL,
  `QSAMP` DECIMAL(10,5) NOT NULL,
  `QNUMB` DECIMAL(10,5) NOT NULL,
  `QHAND` DECIMAL(10,5) NOT NULL,
  `QMETH` DECIMAL(10,5) NOT NULL,
  `QPERFORM` DECIMAL(10,5) NOT NULL,
  `QMATCH` DECIMAL(10,5) NOT NULL,
  `QREPRESEN` DECIMAL(10,5) NOT NULL,
  `QIEUROFIR` VARCHAR(255) NOT NULL DEFAULT '',
  `CCEUROFIR` VARCHAR(255) NOT NULL DEFAULT '',
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`QAID`),
  INDEX `VALUEID` (`VALUEID` ASC),
  INDEX `QREF` (`QREF` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_recipephoto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_recipephoto` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_recipephoto` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `RECID` VARCHAR(255) NOT NULL,
  `MIMETYPE` VARCHAR(255) NULL DEFAULT NULL,
  `FILESIZE` INT(10) NULL DEFAULT NULL,
  `DATA` LONGBLOB NULL DEFAULT NULL,
  `DATEGEN` DATETIME NULL DEFAULT NULL,
  `DATEREV` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Index 2` (`RECID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_reference` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_reference` (
  `SOURCEID` VARCHAR(25) NOT NULL,
  `SRCODE` VARCHAR(255) NOT NULL DEFAULT '',
  `ACQTYPE` VARCHAR(255) NOT NULL DEFAULT '',
  `REFTYPE` VARCHAR(255) NOT NULL DEFAULT '',
  `CITATION` VARCHAR(255) NOT NULL DEFAULT '',
  `TITLE` VARCHAR(255) NOT NULL DEFAULT '',
  `AUTHORS` VARCHAR(255) NOT NULL DEFAULT '',
  `PUBDATE` DATE NOT NULL,
  `VERSION` VARCHAR(255) NOT NULL DEFAULT '',
  `ORIGLANG` VARCHAR(255) NOT NULL DEFAULT '',
  `ISBN` VARCHAR(255) NOT NULL DEFAULT '',
  `FSTEDDAT` DATE NOT NULL,
  `EDNR` INT(11) NOT NULL,
  `NRPAGES` VARCHAR(255) NOT NULL DEFAULT '',
  `BKTITLE` VARCHAR(255) NOT NULL DEFAULT '',
  `EDITORS` VARCHAR(255) NOT NULL DEFAULT '',
  `PAGES` VARCHAR(255) NOT NULL DEFAULT '',
  `LGJRNAME` VARCHAR(255) NOT NULL DEFAULT '',
  `ABJRNAME` VARCHAR(255) NOT NULL DEFAULT '',
  `ISSN` VARCHAR(255) NOT NULL DEFAULT '',
  `VOLUME` VARCHAR(255) NOT NULL DEFAULT '',
  `ISSUE` VARCHAR(255) NOT NULL DEFAULT '',
  `SERINAME` VARCHAR(255) NOT NULL DEFAULT '',
  `SERINR` VARCHAR(255) NOT NULL DEFAULT '',
  `RPRTITLE` VARCHAR(255) NOT NULL DEFAULT '',
  `FILEFRMT` VARCHAR(255) NOT NULL DEFAULT '',
  `WWW` VARCHAR(255) NOT NULL DEFAULT '',
  `MEDIUM` VARCHAR(255) NOT NULL DEFAULT '',
  `OS` VARCHAR(255) NOT NULL DEFAULT '',
  `MEDIA` VARCHAR(255) NOT NULL DEFAULT '',
  `VALID` DATE NOT NULL,
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`SOURCEID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_retentionfactors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_retentionfactors` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_retentionfactors` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FOODID` VARCHAR(25) NOT NULL,
  `COMPID` VARCHAR(25) NOT NULL DEFAULT '',
  `PREPMET` VARCHAR(255) NOT NULL DEFAULT '',
  `TMIN` INT(11) NOT NULL,
  `TMAX` INT(11) NOT NULL,
  `BREADED` VARCHAR(1) NOT NULL,
  `PART` VARCHAR(1) NOT NULL,
  `WHOLE` VARCHAR(1) NOT NULL,
  `SOAK` VARCHAR(1) NOT NULL,
  `FAT` VARCHAR(1) NOT NULL,
  `RETFACT` DECIMAL(10,2) NOT NULL,
  `RETREF` VARCHAR(25) NOT NULL DEFAULT '',
  `REMARK` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  INDEX `FOODID` (`FOODID` ASC),
  INDEX `COMPID` (`COMPID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_sample` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_sample` (
  `SAMPID` VARCHAR(25) NOT NULL,
  `SAMPREF` VARCHAR(25) NOT NULL DEFAULT '',
  `REASON` VARCHAR(255) NOT NULL DEFAULT '',
  `SAMPSRAT` VARCHAR(255) NOT NULL DEFAULT '',
  `PLCECOLL` VARCHAR(255) NOT NULL DEFAULT '',
  `DATSAMPL` VARCHAR(255) NOT NULL DEFAULT '',
  `SPLEUNSIZE` VARCHAR(255) NOT NULL DEFAULT '',
  `SPLEUNNUM` DECIMAL(10,5) NOT NULL,
  `COMPOSITE` TINYINT(1) NULL DEFAULT NULL,
  `SPLEHANDL` VARCHAR(255) NOT NULL DEFAULT '',
  `LABARRIV` DATE NOT NULL,
  `LABSTORE` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`SAMPID`),
  INDEX `SAMPREF` (`SAMPREF` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_thesauri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_thesauri` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_thesauri` (
  `ID` INT(25) NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(25) NOT NULL,
  `DESCRIPTOR` VARCHAR(255) NOT NULL,
  `SCOPEN` VARCHAR(255) NOT NULL,
  `ADDINFO` VARCHAR(255) NOT NULL,
  `SYNONYMS` VARCHAR(255) NOT NULL,
  `RELTERMS` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Code` (`CODE` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `food`.`fir_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`fir_value` ;

CREATE TABLE IF NOT EXISTS `food`.`fir_value` (
  `ORIGFDCD` VARCHAR(25) NOT NULL,
  `COMPID` VARCHAR(25) NOT NULL,
  `VALUEID` VARCHAR(25) NOT NULL DEFAULT '',
  `SELVAL` DOUBLE NOT NULL,
  `UNIT` VARCHAR(255) NOT NULL DEFAULT '',
  `MATRIX` VARCHAR(255) NOT NULL DEFAULT '',
  `VALTYPE` VARCHAR(255) NOT NULL DEFAULT '',
  `ACQTYPE` VARCHAR(255) NOT NULL DEFAULT '',
  `SOURCEID` VARCHAR(255) NOT NULL DEFAULT '',
  `DATEGEN` DATE NOT NULL,
  `DATEEVAL` DATE NOT NULL,
  `QAID` VARCHAR(255) NOT NULL DEFAULT '',
  `N` INT(11) NOT NULL,
  `ANPORT` VARCHAR(255) NOT NULL DEFAULT '',
  `NOANPORT` INT(11) NOT NULL,
  `MEAN` DECIMAL(10,5) NOT NULL,
  `MEDIAN` DECIMAL(10,5) NOT NULL,
  `MIN` DECIMAL(10,5) NOT NULL,
  `MAX` DECIMAL(10,5) NOT NULL,
  `STDV` DECIMAL(10,5) NOT NULL,
  `STERR` DECIMAL(10,5) NOT NULL,
  `METHTYPE` VARCHAR(255) NOT NULL DEFAULT '',
  `METHIND` VARCHAR(255) NOT NULL DEFAULT '',
  `METHPAR` DECIMAL(10,5) NOT NULL,
  `METHID` VARCHAR(255) NOT NULL DEFAULT '',
  `REMARKS` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ORIGFDCD`, `COMPID`, `VALUEID`),
  INDEX `ORIGFDCD` (`ORIGFDCD` ASC),
  INDEX `COMPID` (`COMPID` ASC),
  INDEX `SOURCEID` (`SOURCEID` ASC),
  CONSTRAINT `fk_fir_value_fir_food`
    FOREIGN KEY (`ORIGFDCD`)
    REFERENCES `food`.`fir_food` (`ORIGFDCD`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fir_value_fir_component1`
    FOREIGN KEY (`COMPID`)
    REFERENCES `food`.`fir_component` (`ECOMPID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
