CREATE TABLE IF NOT EXISTS `fitbit_user` (
	`FITBIT_ID` varchar(25) NOT NULL DEFAULT '',
    `ABOUT_ME` text,
    `AGE` int(11) DEFAULT 0,
    `AVATAR` varchar(255) DEFAULT '',
    `AVERAGE_DAILTY_STEPS` decimal(10,5) DEFAULT 0,
    `DATE_OF_BIRTH` datetime DEFAULT NULL,
    `DISPLAY_NAME` varchar(255) DEFAULT '',
    `FULL_NAME` varchar(255) DEFAULT '',
    `DISTANCE_UNIT` varchar(255) DEFAULT '',
    `GENDER` varchar(255) DEFAULT '',
    `GLUCOSE_UNIT` varchar(255) DEFAULT '',
    `HEIGHT` decimal(10,5) DEFAULT 0,
    `HEIGHT_UNIT` varchar(255) DEFAULT '',
    `LOCALE` varchar(255) DEFAULT '',
    `WEIGHT` decimal(10,5) DEFAULT 0,
    `WEIGHT_UNIT` varchar(255) DEFAULT '',
    `TIMEZONE` varchar(255) DEFAULT '',
    `CITY` varchar(255) DEFAULT '',
    `COUNTRY` varchar(255) DEFAULT '',
    PRIMARY KEY (`FITBIT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `fc_celiac_members` (
  `CODE` varchar(255) NOT NULL DEFAULT '',
  `FIRST_NAME` varchar(255) NOT NULL DEFAULT '',
  `LAST_NAME` varchar(255) NOT NULL DEFAULT '',
  `CREATED` datetime DEFAULT NULL,
  `MODIFIED` datetime DEFAULT NULL,
  PRIMARY KEY (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_diet` (
  `DIETID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DIETNM` varchar(255) NOT NULL,
  `DENGNM` varchar(255) NOT NULL,
  `DIETDESC` text NOT NULL,
  `DENGDESC` text NOT NULL,
  `AUTHORID` int(11) NOT NULL,
  PRIMARY KEY (`DIETID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=12 ;

CREATE TABLE IF NOT EXISTS `fc_ematerials` (
  `EMID` int(11) NOT NULL,
  `EDUMAT` blob NOT NULL,
  `EMENG` blob NOT NULL,
  `DATEGEN` date NOT NULL,
  `DATEREV` date NOT NULL,
  `TRID` int(11) NOT NULL,
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`EMID`),
  KEY `TRID` (`TRID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_exchangesystem` (
  `FGID` int(11) NOT NULL,
  `COMPID` varchar(25) NOT NULL,
  `MIN` int(11) NOT NULL,
  `MAXL` int(11) NOT NULL,
  `MAXU` int(11) NOT NULL,
  `UNIT` varchar(25) NOT NULL,
  `SOURCEID` int(11) NOT NULL,
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  KEY `FGID` (`FGID`),
  KEY `COMPID` (`COMPID`),
  KEY `SOURCEID` (`SOURCEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_ffqs` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) DEFAULT NULL,
  `ContentId` int(11) DEFAULT NULL,
  `Recurrence` varchar(50) DEFAULT NULL,
  `OnlyMediumSize` tinyint(4) NOT NULL DEFAULT '0',
  `AllSizes` tinyint(4) NOT NULL DEFAULT '0',
  `RemarksLabel` varchar(255) DEFAULT NULL,
  `Created` datetime DEFAULT NULL,
  `Modified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

CREATE TABLE IF NOT EXISTS `fc_ffq_pictures` (
  `StepId` int(10) NOT NULL DEFAULT '0',
  `FoodName` varchar(255) NOT NULL DEFAULT '',
  `Size` varchar(32) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `FFQ_ID` int(11) DEFAULT NULL,
  `Picture` longblob,
  `Weight` decimal(10,5) DEFAULT NULL,
  `WeightDesc` varchar(255) DEFAULT NULL,
  `Ts` datetime DEFAULT NULL,
  PRIMARY KEY (`StepId`,`FoodName`,`Size`),
  KEY `ByFFQ` (`FFQ_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_ffq_steps` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `FFQ_ID` int(10) NOT NULL DEFAULT '0',
  `Question` varchar(255) DEFAULT NULL,
  `StepNumber` int(11) NOT NULL DEFAULT '1',
  `Type` varchar(50) DEFAULT NULL,
  `Instructions` text,
  `AllowSkipTo` int(11) DEFAULT NULL,
  `FoodCodes` text,
  `WeightS` decimal(10,5) DEFAULT NULL,
  `WeightTextS` varchar(255) DEFAULT NULL,
  `WeightM` decimal(10,5) DEFAULT NULL,
  `WeightTextM` varchar(255) DEFAULT NULL,
  `WeightL` decimal(10,5) DEFAULT NULL,
  `WeightTextL` varchar(255) DEFAULT NULL,
  `WeightXL` decimal(10,5) DEFAULT NULL,
  `WeightTextXL` varchar(255) DEFAULT NULL,
  `WeightXXL` decimal(10,5) DEFAULT NULL,
  `WeightTextXXL` varchar(255) DEFAULT NULL,
  `WeightXXXL` decimal(10,5) DEFAULT NULL,
  `WeightTextXXXL` varchar(255) DEFAULT NULL,
  `Frequency1` varchar(25) DEFAULT NULL,
  `Frequency2` varchar(25) DEFAULT NULL,
  `Frequency3` varchar(25) DEFAULT NULL,
  `Frequency4` varchar(25) DEFAULT NULL,
  `Frequency5` varchar(25) DEFAULT NULL,
  `Frequency6` varchar(25) DEFAULT NULL,
  `Frequency7` varchar(25) DEFAULT NULL,
  `Frequency8` varchar(25) DEFAULT NULL,
  `Frequency9` varchar(25) DEFAULT NULL,
  `Frequency10` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ByFFQ` (`FFQ_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=176 ;

CREATE TABLE IF NOT EXISTS `fc_ffq_warnings` (
  `ID` int(10) NOT NULL DEFAULT '0',
  `Result` varchar(255) DEFAULT NULL,
  `Description` text,
  `Url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_foodalternatives` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DIETID` int(11) NOT NULL,
  `ORIGFDCD` varchar(25) NOT NULL,
  `ALTFDCD` varchar(25) NOT NULL,
  `AFAMFAC` decimal(10,5) NOT NULL,
  `AUTHORID` int(11) NOT NULL,
  `DATEGEN` datetime NOT NULL,
  `DATEREV` datetime NOT NULL,
  `REMARKS` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `Index 2` (`ORIGFDCD`,`DIETID`,`ALTFDCD`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=272 ;

CREATE TABLE IF NOT EXISTS `fc_foodgroup` (
  `FGCD` int(11) NOT NULL,
  `FGNM` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `FGENGNM` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `FGDESC` text CHARACTER SET utf8 NOT NULL,
  `FGENGDESC` text CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`FGCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `fc_foodprices` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `FOODID` varchar(25) DEFAULT NULL,
  `PRICE` decimal(15,2) DEFAULT NULL,
  `CURRENCY` varchar(10) DEFAULT NULL,
  `STOREID` int(11) DEFAULT NULL,
  `WEIGHT` decimal(15,2) DEFAULT NULL,
  `UNIT` varchar(50) DEFAULT NULL,
  `USERID` int(11) DEFAULT NULL,
  `DATEGEN` datetime DEFAULT NULL,
  `DATEREV` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ByFood` (`FOODID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=94 ;

CREATE TABLE IF NOT EXISTS `fc_foodquestionnaire` (
  `FQCD` int(11) NOT NULL,
  `GSAMIN` decimal(10,5) NOT NULL,
  `GSAMAX` decimal(10,5) NOT NULL,
  `GRADEA` varchar(255) NOT NULL,
  `GSBMIN` decimal(10,5) NOT NULL,
  `GSBMAX` decimal(10,5) NOT NULL,
  `GRADEB` varchar(255) NOT NULL,
  `GSCMIN` decimal(10,5) NOT NULL,
  `GSCMAX` decimal(10,5) NOT NULL,
  `GRADEC` varchar(255) NOT NULL,
  `AUTHID` int(11) NOT NULL,
  `DATEGEN` datetime NOT NULL,
  `DATEREV` datetime NOT NULL,
  `REMARKS` varchar(255) NOT NULL,
  PRIMARY KEY (`FQCD`),
  KEY `AUTHID` (`AUTHID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_foodstores` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) DEFAULT NULL,
  `ACTIVE` tinyint(4) NOT NULL DEFAULT '0',
  `USERID` int(11) DEFAULT NULL,
  `DATEGEN` datetime DEFAULT NULL,
  `DATEREV` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=30 ;

CREATE TABLE IF NOT EXISTS `fc_foodsubgroup` (
  `FSGCD` int(11) NOT NULL,
  `FSGNM` varchar(255) NOT NULL,
  `FSGENGNM` varchar(255) NOT NULL,
  `FGCD` int(11) NOT NULL,
  `FDBFID` varchar(25) NOT NULL,
  `FDSFKID` varchar(25) NOT NULL,
  `FDUSDAID` varchar(25) NOT NULL,
  `FDINDID` varchar(25) NOT NULL,
  PRIMARY KEY (`FSGCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_fqquestions` (
  `FQCD` int(11) NOT NULL,
  `QCD` int(11) NOT NULL,
  `QUES` text NOT NULL,
  `INSTR` varchar(255) NOT NULL,
  `COMMENT` varchar(255) NOT NULL,
  `ANS1` varchar(255) NOT NULL,
  `POINTS1` int(11) NOT NULL,
  `ANS2` varchar(255) NOT NULL,
  `POINTS2` int(11) NOT NULL,
  `ANS3` varchar(255) NOT NULL,
  `POINTS3` int(11) NOT NULL,
  `ANS4` varchar(255) NOT NULL,
  `POINTS4` int(11) NOT NULL,
  `ANS5` varchar(255) NOT NULL,
  `POINTS5` int(11) NOT NULL,
  `ANS6` varchar(255) NOT NULL,
  `POINTS6` int(11) NOT NULL,
  `ANS7` varchar(255) NOT NULL,
  `POINTS7` int(11) NOT NULL,
  `ANS8` varchar(255) NOT NULL,
  `POINTS8` int(11) NOT NULL,
  `ANS9` varchar(255) NOT NULL,
  `POINTS9` int(11) NOT NULL,
  `ANS10` varchar(255) NOT NULL,
  `POINTS10` int(11) NOT NULL,
  `PMAX` int(11) NOT NULL,
  `ORDER` int(11) NOT NULL,
  PRIMARY KEY (`QCD`),
  KEY `FQCD` (`FQCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_gastro` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ENGNAME` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CREATED` datetime DEFAULT NULL,
  `MODIFIED` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=12 ;

CREATE TABLE IF NOT EXISTS `fc_groupofpeople` (
  `GPID` int(11) NOT NULL,
  `GPNM` varchar(255) NOT NULL DEFAULT '',
  `GPENGNM` varchar(255) NOT NULL DEFAULT '',
  `GPDESC` text NOT NULL,
  `GPENGDESC` text NOT NULL,
  `SEX` varchar(255) NOT NULL DEFAULT '',
  `MIN` int(11) NOT NULL,
  `MAX` int(11) NOT NULL,
  `UNIT` varchar(255) NOT NULL DEFAULT '',
  `WEIGHT` decimal(10,5) DEFAULT NULL,
  `HEIGHT` decimal(10,5) DEFAULT NULL,
  `SOURCEID` int(11) NOT NULL,
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`GPID`),
  KEY `SOURCEID` (`SOURCEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_gs1` (
  `FOODID` varchar(25) NOT NULL,
  `GS1` varchar(255) NOT NULL,
  `DISTRIB` varchar(255) DEFAULT NULL,
  `COUNTRY` varchar(255) DEFAULT NULL,
  `PRODUCER` varchar(255) DEFAULT NULL,
  `REMARKS` varchar(255) DEFAULT NULL,
  `DATEGEN` datetime DEFAULT NULL,
  `DATEREV` datetime DEFAULT NULL,
  PRIMARY KEY (`FOODID`,`GS1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_guidelines` (
  `GPID` int(11) NOT NULL,
  `COMPID` varchar(25) NOT NULL,
  `FGID` varchar(25) NOT NULL,
  `MEALCD` varchar(25) NOT NULL,
  `VALUE` decimal(10,5) NOT NULL,
  `MIN` decimal(10,5) NOT NULL,
  `MAX` decimal(10,5) NOT NULL,
  `UNIT` varchar(255) NOT NULL,
  `VALTYPE` varchar(255) NOT NULL,
  `SOURCEID` int(11) NOT NULL,
  `DATEGEN` datetime NOT NULL,
  `DATEREV` datetime NOT NULL,
  `REMARKS` varchar(255) NOT NULL,
  PRIMARY KEY (`GPID`,`COMPID`,`FGID`,`MEALCD`),
  KEY `GPID` (`GPID`),
  KEY `COMPID` (`COMPID`),
  KEY `FGID` (`FGID`),
  KEY `SOURCEID` (`SOURCEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `fc_householdmeasure` (
  `HMCD` int(11) NOT NULL AUTO_INCREMENT,
  `HMNM` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `HMENGNM` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`HMCD`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC AUTO_INCREMENT=1924 ;

CREATE TABLE IF NOT EXISTS `fc_kulinarika` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) NOT NULL,
  `DATEGEN` datetime DEFAULT NULL,
  `DATEREV` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=20 ;

CREATE TABLE IF NOT EXISTS `fc_lllclassroom` (
  `USERID` int(11) NOT NULL,
  `LLLMID` int(11) NOT NULL,
  `DATE` datetime NOT NULL,
  `GRADE` decimal(10,5) NOT NULL,
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  KEY `USERID` (`USERID`),
  KEY `LLLMID` (`LLLMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_lllmodul` (
  `LLLMID` int(11) NOT NULL,
  `LLLMNM` varchar(255) NOT NULL DEFAULT '',
  `LLLMC` text NOT NULL,
  `TRID` int(11) NOT NULL,
  `DATEGEN` date NOT NULL,
  `DATEREV` date NOT NULL,
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`LLLMID`),
  KEY `TRID` (`TRID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_llltest` (
  `LLLMID` int(11) NOT NULL,
  `LLLMQ` varchar(255) NOT NULL,
  `LLLMAA` varchar(255) NOT NULL DEFAULT '',
  `LLLMAB` varchar(255) NOT NULL DEFAULT '',
  `LLLMAC` varchar(255) NOT NULL DEFAULT '',
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`LLLMQ`),
  KEY `LLLMID` (`LLLMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_mapping` (
  `FDNM` varchar(255) NOT NULL,
  `FDENGNM` varchar(255) NOT NULL,
  `FDBFID` varchar(25) NOT NULL,
  `FDSFKID` varchar(25) NOT NULL,
  `FDUSDAID` varchar(25) NOT NULL,
  `FDINDID` varchar(25) NOT NULL,
  PRIMARY KEY (`FDBFID`,`FDSFKID`,`FDUSDAID`,`FDINDID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_mappingind` (
  `FDNM` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `FDENGNM` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `FDBFID` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `FDSFKID` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `FDUSDAID` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `FDINDID` varchar(25) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `fc_mapping_20130516` (
  `FDNM` varchar(255) NOT NULL,
  `FDENGNM` varchar(255) NOT NULL,
  `FDBFID` varchar(25) NOT NULL,
  `FDSFKID` varchar(25) NOT NULL,
  `FDUSDAID` varchar(25) NOT NULL,
  `FDINDID` varchar(25) NOT NULL,
  PRIMARY KEY (`FDBFID`,`FDSFKID`,`FDUSDAID`,`FDINDID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `fc_meal` (
  `MEALCD` varchar(25) NOT NULL,
  `MEALNM` varchar(255) NOT NULL,
  `MENGNM` varchar(255) NOT NULL,
  `FROM` time DEFAULT NULL,
  `TO` time DEFAULT NULL,
  `GROUP` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`MEALCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_menucls` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;

CREATE TABLE IF NOT EXISTS `fc_menutags` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `CLSID` int(10) DEFAULT '0',
  `NAME` varchar(255) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `CLS` (`CLSID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=30 ;

CREATE TABLE IF NOT EXISTS `fc_municipality` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=211 ;

CREATE TABLE IF NOT EXISTS `fc_pal` (
  `PAID` int(11) NOT NULL AUTO_INCREMENT,
  `PAG` varchar(255) NOT NULL,
  `PADESC` varchar(255) NOT NULL DEFAULT '',
  `PAENGDESC` varchar(255) NOT NULL DEFAULT '',
  `SEX` varchar(1) NOT NULL,
  `PAL` decimal(10,5) NOT NULL,
  `METS` decimal(10,5) NOT NULL,
  `UNIT` varchar(25) NOT NULL,
  `SOURCEID` varchar(25) NOT NULL,
  `REMARKS` varchar(255) NOT NULL,
  `TYPE` char(10) DEFAULT 'A',
  PRIMARY KEY (`PAID`),
  KEY `SOURCEID` (`SOURCEID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=677 ;

CREATE TABLE IF NOT EXISTS `fc_percentile` (
  `SEX` varchar(1) NOT NULL,
  `MONTH` int(11) NOT NULL,
  `TYPE` varchar(50) DEFAULT NULL,
  `L` double DEFAULT NULL,
  `M` double DEFAULT NULL,
  `S` double DEFAULT NULL,
  `P1` double DEFAULT NULL,
  `P3` double DEFAULT NULL,
  `P5` double DEFAULT NULL,
  `P10` double DEFAULT NULL,
  `P15` double DEFAULT NULL,
  `P25` double DEFAULT NULL,
  `P50` double DEFAULT NULL,
  `P75` double DEFAULT NULL,
  `P85` double DEFAULT NULL,
  `P90` double DEFAULT NULL,
  `P95` double DEFAULT NULL,
  `P97` double DEFAULT NULL,
  `P99` double DEFAULT NULL,
  PRIMARY KEY (`SEX`,`MONTH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_recall_categories` (
  `IVZFDCD` varchar(35) NOT NULL,
  `FGCD` int(11) NOT NULL,
  `IVZFDNM` varchar(255) NOT NULL,
  `ENGFDNM` varchar(255) NOT NULL,
  `LEVEL` int(11) NOT NULL,
  `FOODEX1` varchar(35) NOT NULL,
  `FOODEX2` varchar(35) NOT NULL,
  `ORIGFDCD` varchar(35) NOT NULL,
  PRIMARY KEY (`IVZFDCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_recall_category_pictureweight` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `IVZFDCD` varchar(35) DEFAULT NULL,
  `PICTURE` longblob,
  `WEIGHT` decimal(10,5) DEFAULT NULL,
  `DATEGEN` datetime DEFAULT NULL,
  `DATEREV` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ByCode` (`IVZFDCD`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=479 ;

CREATE TABLE IF NOT EXISTS `fc_subkulinarika` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CATID` int(11) NOT NULL,
  `TITLE` varchar(255) NOT NULL,
  `CLASSIFIER` varchar(255) NOT NULL,
  `DATEGEN` datetime DEFAULT NULL,
  `DATEREV` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=47 ;

CREATE TABLE IF NOT EXISTS `fc_weights` (
  `ORIGFDCD` varchar(25) NOT NULL,
  `HMCD` int(11) unsigned NOT NULL,
  `AMOUNT` double NOT NULL,
  `IMAGE` blob NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fc_yieldfactors` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FOODID` varchar(25) DEFAULT NULL,
  `PREPMET` varchar(255) DEFAULT NULL,
  `TMIN` int(11) NOT NULL,
  `TMAX` int(11) NOT NULL,
  `YIELD` decimal(10,5) NOT NULL,
  `YNM` varchar(255) DEFAULT NULL,
  `YENGNM` varchar(255) DEFAULT NULL,
  `RETREF` varchar(25) DEFAULT NULL,
  `REMARK` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=667 ;

CREATE TABLE IF NOT EXISTS `fir_component` (
  `ECOMPID` varchar(25) NOT NULL,
  `ORIGCPCD` varchar(25) NOT NULL DEFAULT '',
  `ORIGCPNM` varchar(255) NOT NULL DEFAULT '',
  `ENGCPNAM` varchar(255) NOT NULL DEFAULT '',
  `OPTIJED` varchar(25) NOT NULL,
  `IZVOR` varchar(1) NOT NULL,
  `DACH` varchar(25) NOT NULL,
  `DACH2` varchar(25) NOT NULL,
  `CPID_USDA` varchar(3) NOT NULL,
  `CPDESC` longtext NOT NULL,
  `CPMUCH` longtext NOT NULL,
  `CPLESS` longtext NOT NULL,
  `CPUNITH` varchar(25) NOT NULL,
  `CPUNITP` varchar(25) NOT NULL,
  PRIMARY KEY (`ECOMPID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fir_food` (
  `ORIGFDCD` varchar(25) NOT NULL,
  `ORIGFDNM` varchar(255) NOT NULL DEFAULT '',
  `ENGFDNAM` varchar(255) NOT NULL DEFAULT '',
  `SCINAM` varchar(255) NOT NULL DEFAULT '',
  `CDXFDSTD` varchar(255) NOT NULL DEFAULT '',
  `GS1` varchar(255) NOT NULL DEFAULT '',
  `ENR` varchar(255) NOT NULL DEFAULT '',
  `INS` varchar(255) NOT NULL DEFAULT '',
  `ORIGGPCD` varchar(25) NOT NULL DEFAULT '',
  `FSGCD` int(11) DEFAULT NULL,
  `PRODTYPE` varchar(255) NOT NULL,
  `CDXFDADD` varchar(255) NOT NULL DEFAULT '',
  `CDXFDFD` varchar(255) NOT NULL DEFAULT '',
  `CDXCONT` varchar(255) NOT NULL DEFAULT '',
  `FAOFBS` varchar(255) NOT NULL DEFAULT '',
  `CIAA` varchar(255) NOT NULL DEFAULT '',
  `EC2` varchar(255) NOT NULL DEFAULT '',
  `FOODSRCE` varchar(255) NOT NULL,
  `PARTPLAN` varchar(255) NOT NULL,
  `PHYSTATE` varchar(255) NOT NULL,
  `HEATREAT` varchar(255) NOT NULL,
  `COOKMETH` varchar(255) NOT NULL,
  `TREATAPP` varchar(255) NOT NULL,
  `PRESMETH` varchar(255) NOT NULL,
  `PACKMED` varchar(255) NOT NULL,
  `CONTWRPG` varchar(255) NOT NULL,
  `FDCTSRFC` varchar(255) NOT NULL,
  `LBLCLAIM` varchar(255) NOT NULL,
  `AREAORIG` varchar(255) NOT NULL,
  `AREAPROC` varchar(255) NOT NULL DEFAULT '',
  `AREACONS` varchar(255) NOT NULL DEFAULT '',
  `PRODENVIR` varchar(255) NOT NULL,
  `AGRICOND` varchar(255) NOT NULL DEFAULT '',
  `GROWCOND` varchar(255) NOT NULL DEFAULT '',
  `MATURITY` varchar(255) NOT NULL DEFAULT '',
  `GENMOD` varchar(255) NOT NULL DEFAULT '',
  `CUISINE` varchar(255) NOT NULL DEFAULT '',
  `ADJUNCT` varchar(255) NOT NULL DEFAULT '',
  `INGLIST` varchar(255) NOT NULL DEFAULT '',
  `FINLPREP` varchar(255) NOT NULL DEFAULT '',
  `SERVSIZE` varchar(255) NOT NULL DEFAULT '',
  `SERVPACK` decimal(10,5) NOT NULL,
  `SERVSUGG` varchar(255) NOT NULL DEFAULT '',
  `PREPSTATE` tinyint(1) NOT NULL,
  `YIELD` varchar(25) NOT NULL,
  `ALLERGEN` varchar(255) NOT NULL DEFAULT '',
  `DIETCLAIM` varchar(255) NOT NULL DEFAULT '',
  `EDPORTNAT` varchar(255) NOT NULL DEFAULT '',
  `WASTENAT` varchar(255) NOT NULL DEFAULT '',
  `COLOR` varchar(255) NOT NULL DEFAULT '',
  `GENIMAGE` varchar(255) NOT NULL DEFAULT '',
  `SPCIMAGE` varchar(255) NOT NULL DEFAULT '',
  `PRODUCER` varchar(255) NOT NULL DEFAULT '',
  `DISTRIB` varchar(255) NOT NULL DEFAULT '',
  `SOURCEID` varchar(25) DEFAULT NULL,
  `COUNTRY` varchar(255) DEFAULT NULL,
  `DIETID` varchar(255) DEFAULT NULL,
  `GASTROID` varchar(255) DEFAULT NULL,
  `FOODEX2` varchar(255) DEFAULT NULL,
  `KULINARIKA_CAT` int(11) DEFAULT NULL,
  `KULINARIKA_SUBCAT` int(11) DEFAULT NULL,
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  `ACTIVE` char(1) NOT NULL DEFAULT '',
  `DATEGEN` datetime DEFAULT NULL,
  `DATEREV` datetime DEFAULT NULL,
  PRIMARY KEY (`ORIGFDCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fir_foodnames` (
  `ORIGFDCD` varchar(25) NOT NULL,
  `FNAME` varchar(255) NOT NULL DEFAULT '',
  `LANG` varchar(255) NOT NULL DEFAULT '',
  `PREF` varchar(255) NOT NULL DEFAULT '',
  `FNREF` varchar(255) NOT NULL DEFAULT '',
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`FNAME`,`ORIGFDCD`),
  KEY `ORIGFDCD` (`ORIGFDCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fir_food_new` (
  `ORIGFDCD` varchar(255) NOT NULL DEFAULT '',
  `SLO` varchar(255) DEFAULT NULL,
  `ENG` varchar(255) DEFAULT NULL,
  `SCI` varchar(255) DEFAULT NULL,
  `GROUP` int(11) DEFAULT NULL,
  `VIS` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ORIGFDCD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fir_ingredients` (
  `RECID` varchar(25) NOT NULL,
  `FOODID` varchar(25) NOT NULL,
  `INGNAM` varchar(255) NOT NULL DEFAULT '',
  `INGAMOUNT` decimal(15,5) NOT NULL,
  `INGUNIT` varchar(255) NOT NULL DEFAULT '',
  `HMID` int(3) NOT NULL DEFAULT '0',
  `RANK` int(11) NOT NULL,
  `EDIBLE` tinyint(3) NOT NULL DEFAULT '0',
  `WHOLE_WHEAT` tinyint(3) NOT NULL DEFAULT '0',
  `SOAK` tinyint(3) NOT NULL DEFAULT '0',
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`RECID`,`FOODID`),
  KEY `RECID` (`RECID`),
  KEY `FOODID` (`FOODID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fir_method` (
  `METHID` varchar(25) NOT NULL DEFAULT '',
  `METHNAME` varchar(255) NOT NULL DEFAULT '',
  `ORGMNAM` varchar(255) NOT NULL DEFAULT '',
  `OFFICIAL` varchar(255) NOT NULL DEFAULT '',
  `GENDESC` varchar(255) NOT NULL DEFAULT '',
  `METHREF` varchar(255) NOT NULL DEFAULT '',
  `EXTRACT` varchar(255) NOT NULL DEFAULT '',
  `SEPARAT` varchar(255) NOT NULL DEFAULT '',
  `IDENT` varchar(255) NOT NULL DEFAULT '',
  `DETECT` varchar(255) NOT NULL DEFAULT '',
  `QUANT` varchar(255) NOT NULL DEFAULT '',
  `OMETHKS` varchar(255) NOT NULL DEFAULT '',
  `ADDDESC` varchar(255) NOT NULL DEFAULT '',
  `ANDETAIL` varchar(255) NOT NULL DEFAULT '',
  `ACCURACY` varchar(255) NOT NULL DEFAULT '',
  `APPLICABILITY` varchar(255) NOT NULL DEFAULT '',
  `PRECISION` decimal(10,5) NOT NULL,
  `REPEAT` decimal(10,5) NOT NULL,
  `REPRODUC` decimal(10,5) NOT NULL,
  `RECOVERY` decimal(10,5) NOT NULL,
  `SELECTIV` decimal(10,5) NOT NULL,
  `SENSITIV` decimal(10,5) NOT NULL,
  `SPECIFIC` decimal(10,5) NOT NULL,
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`METHID`),
  KEY `METHREF` (`METHREF`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fir_qualityassessment` (
  `VALUEID` varchar(25) NOT NULL,
  `QAID` varchar(25) NOT NULL DEFAULT '',
  `QDESC` varchar(255) NOT NULL DEFAULT '',
  `QREF` varchar(25) NOT NULL DEFAULT '',
  `QFOOD` decimal(10,5) NOT NULL,
  `QCOMP` decimal(10,5) NOT NULL,
  `QSAMP` decimal(10,5) NOT NULL,
  `QNUMB` decimal(10,5) NOT NULL,
  `QHAND` decimal(10,5) NOT NULL,
  `QMETH` decimal(10,5) NOT NULL,
  `QPERFORM` decimal(10,5) NOT NULL,
  `QMATCH` decimal(10,5) NOT NULL,
  `QREPRESEN` decimal(10,5) NOT NULL,
  `QIEUROFIR` varchar(255) NOT NULL DEFAULT '',
  `CCEUROFIR` varchar(255) NOT NULL DEFAULT '',
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`QAID`),
  KEY `VALUEID` (`VALUEID`),
  KEY `QREF` (`QREF`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fir_recipe` (
  `ORIGFDCD` varchar(25) NOT NULL,
  `RECID` varchar(25) NOT NULL,
  `RECREF` varchar(25) NOT NULL DEFAULT '',
  `RECPROC` longtext NOT NULL,
  `YIELDWAT` decimal(10,5) NOT NULL,
  `AUTHOR` varchar(255) NOT NULL,
  `YIELDFAT` decimal(10,5) NOT NULL,
  `YIELDALC` decimal(10,5) NOT NULL,
  `RETREF` varchar(25) NOT NULL DEFAULT '',
  `IS_DRAINED` tinyint(4) NOT NULL DEFAULT '0',
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`RECID`),
  KEY `ORIGFDCD` (`ORIGFDCD`),
  KEY `RECREF` (`RECREF`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fir_recipephoto` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `RECID` varchar(255) NOT NULL,
  `MIMETYPE` varchar(255) DEFAULT NULL,
  `FILESIZE` int(10) DEFAULT NULL,
  `DATA` longblob,
  `DATEGEN` datetime DEFAULT NULL,
  `DATEREV` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `Index 2` (`RECID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1349 ;

CREATE TABLE IF NOT EXISTS `fir_reference` (
  `SOURCEID` varchar(25) NOT NULL,
  `SRCODE` varchar(255) NOT NULL DEFAULT '',
  `ACQTYPE` varchar(255) NOT NULL DEFAULT '',
  `REFTYPE` varchar(255) NOT NULL DEFAULT '',
  `CITATION` varchar(255) NOT NULL DEFAULT '',
  `TITLE` varchar(255) NOT NULL DEFAULT '',
  `AUTHORS` varchar(255) NOT NULL DEFAULT '',
  `PUBDATE` date NOT NULL,
  `VERSION` varchar(255) NOT NULL DEFAULT '',
  `ORIGLANG` varchar(255) NOT NULL DEFAULT '',
  `ISBN` varchar(255) NOT NULL DEFAULT '',
  `FSTEDDAT` date NOT NULL,
  `EDNR` int(11) NOT NULL,
  `NRPAGES` varchar(255) NOT NULL DEFAULT '',
  `BKTITLE` varchar(255) NOT NULL DEFAULT '',
  `EDITORS` varchar(255) NOT NULL DEFAULT '',
  `PAGES` varchar(255) NOT NULL DEFAULT '',
  `LGJRNAME` varchar(255) NOT NULL DEFAULT '',
  `ABJRNAME` varchar(255) NOT NULL DEFAULT '',
  `ISSN` varchar(255) NOT NULL DEFAULT '',
  `VOLUME` varchar(255) NOT NULL DEFAULT '',
  `ISSUE` varchar(255) NOT NULL DEFAULT '',
  `SERINAME` varchar(255) NOT NULL DEFAULT '',
  `SERINR` varchar(255) NOT NULL DEFAULT '',
  `RPRTITLE` varchar(255) NOT NULL DEFAULT '',
  `FILEFRMT` varchar(255) NOT NULL DEFAULT '',
  `WWW` varchar(255) NOT NULL DEFAULT '',
  `MEDIUM` varchar(255) NOT NULL DEFAULT '',
  `OS` varchar(255) NOT NULL DEFAULT '',
  `MEDIA` varchar(255) NOT NULL DEFAULT '',
  `VALID` date NOT NULL,
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`SOURCEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fir_retentionfactors` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FOODID` varchar(25) NOT NULL,
  `COMPID` varchar(25) NOT NULL DEFAULT '',
  `PREPMET` varchar(255) NOT NULL DEFAULT '',
  `TMIN` int(11) NOT NULL,
  `TMAX` int(11) NOT NULL,
  `BREADED` varchar(1) NOT NULL,
  `PART` varchar(1) NOT NULL,
  `WHOLE` varchar(1) NOT NULL,
  `SOAK` varchar(1) NOT NULL,
  `FAT` varchar(1) NOT NULL,
  `RETFACT` decimal(10,2) NOT NULL,
  `RETREF` varchar(25) NOT NULL DEFAULT '',
  `REMARK` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `FOODID` (`FOODID`),
  KEY `COMPID` (`COMPID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=20210 ;

CREATE TABLE IF NOT EXISTS `fir_sample` (
  `SAMPID` varchar(25) NOT NULL,
  `SAMPREF` varchar(25) NOT NULL DEFAULT '',
  `REASON` varchar(255) NOT NULL DEFAULT '',
  `SAMPSRAT` varchar(255) NOT NULL DEFAULT '',
  `PLCECOLL` varchar(255) NOT NULL DEFAULT '',
  `DATSAMPL` varchar(255) NOT NULL DEFAULT '',
  `SPLEUNSIZE` varchar(255) NOT NULL DEFAULT '',
  `SPLEUNNUM` decimal(10,5) NOT NULL,
  `COMPOSITE` tinyint(1) DEFAULT NULL,
  `SPLEHANDL` varchar(255) NOT NULL DEFAULT '',
  `LABARRIV` date NOT NULL,
  `LABSTORE` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`SAMPID`),
  KEY `SAMPREF` (`SAMPREF`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `fir_thesauri` (
  `ID` int(25) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(25) NOT NULL,
  `DESCRIPTOR` varchar(255) NOT NULL,
  `SCOPEN` varchar(255) NOT NULL,
  `ADDINFO` varchar(255) NOT NULL,
  `SYNONYMS` varchar(255) NOT NULL,
  `RELTERMS` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `Code` (`CODE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6116 ;

CREATE TABLE IF NOT EXISTS `fir_value` (
  `ORIGFDCD` varchar(25) NOT NULL,
  `COMPID` varchar(25) NOT NULL,
  `VALUEID` varchar(25) NOT NULL DEFAULT '',
  `SELVAL` double NOT NULL,
  `UNIT` varchar(255) NOT NULL DEFAULT '',
  `MATRIX` varchar(255) NOT NULL DEFAULT '',
  `VALTYPE` varchar(255) NOT NULL DEFAULT '',
  `ACQTYPE` varchar(255) NOT NULL DEFAULT '',
  `SOURCEID` varchar(255) NOT NULL DEFAULT '',
  `DATEGEN` date NOT NULL,
  `DATEEVAL` date NOT NULL,
  `QAID` varchar(255) NOT NULL DEFAULT '',
  `N` int(11) NOT NULL,
  `ANPORT` varchar(255) NOT NULL DEFAULT '',
  `NOANPORT` int(11) NOT NULL,
  `MEAN` decimal(10,5) NOT NULL,
  `MEDIAN` decimal(10,5) NOT NULL,
  `MIN` decimal(10,5) NOT NULL,
  `MAX` decimal(10,5) NOT NULL,
  `STDV` decimal(10,5) NOT NULL,
  `STERR` decimal(10,5) NOT NULL,
  `METHTYPE` varchar(255) NOT NULL DEFAULT '',
  `METHIND` varchar(255) NOT NULL DEFAULT '',
  `METHPAR` decimal(10,5) NOT NULL,
  `METHID` varchar(255) NOT NULL DEFAULT '',
  `REMARKS` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ORIGFDCD`,`COMPID`,`VALUEID`),
  KEY `ORIGFDCD` (`ORIGFDCD`),
  KEY `COMPID` (`COMPID`),
  KEY `SOURCEID` (`SOURCEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
