DROP TABLE IF EXISTS A;
DROP TABLE IF EXISTS B;
DROP TABLE IF EXISTS C;
DROP TABLE IF EXISTS D;
DROP TABLE IF EXISTS E;

CREATE TABLE C (
  C_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(45) NULL);

CREATE TABLE A (
   A_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(45) NULL,
  C_ID INT);

CREATE TABLE E (
  E_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(45) NULL);

CREATE TABLE B (
  B_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(45) NULL,
  E_ID INT,
  C_ID INT);

CREATE TABLE D (
  D_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(45) NULL,
  B_ID INT,
  C_ID INT);
